### ISSUE TITLE
App tests follow-up

### ISSUE THREAD

**Issue by GreysonElkins** [GreysonElkins/abstractify#20]
- [x] App renders `MainPage` on route `set/:id`, #6 
- [x] App renders `UserPage` on route `your/sets` #7 
- [x] App renders `PopUpPane` correctly per button press #12
