### ISSUE TITLE
App

### ISSUE THREAD

**Issue by GreysonElkins** [GreysonElkins/abstractify#5]
#### state 
- [x] foreign image sets
- [x] saved sets
- [x] popUpTrigger
#### componentDidMount
- [x] fetch a new current image set

- [x] update images to seen function
- [x] call ^ function on refresh

#### render 
- [x] Header #8 
- [x] MainPage #6 (_route_ `/set/:id`)
- [x] UserPage #7 (_route_ `/your-sets`)
- [x] PopUpPane #12 (_route_ `/save-set` or `/about`)
